services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:z
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
    depends_on:
      - postgres

  vue:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app:z
      - /app/node_modules
    ports:
      - "5173:5173"  # Adjust to your Vue dev server port
    command: npm run dev
    environment:
      NODE_ENV: development

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
